# whosthere configuration file
# For more information, visit: https://github.com/ramonvermeulen/whosthere

# How often to run discovery scans
scan_interval: 20s

# Maximum duration for each scan
scan_duration: 10s

# Splash screen configuration
splash:
  enabled: false

# Theme configuration
theme:
  # When disabled, the TUI will use the terminal it's default ANSI colors
  # Also see the NO_COLOR environment variable to completely disable ANSI colors
  enabled: true
  # See the complete list of available themes at https://github.com/ramonvermeulen/whosthere/tree/main/internal/ui/theme/theme.go
  # Set name to "custom" to use the custom colors below
  # For any color that is not configured it will take the default theme value as fallback
  name: custom

  # Custom theme colors (uncomment and set name: custom to use)
  primitive_background_color: "#c6b3a0"
  contrast_background_color: "#c6b3a0"
  more_contrast_background_color: "#c6b3a0"
  border_color: "#000000"
  title_color: "#000000"
  graphics_color: "#000000"
  primary_text_color: "#000000"
  secondary_text_color: "#000000"
  tertiary_text_color: "#000000"
  inverse_text_color: "#0000000"
  contrast_secondary_text_color: "#000000"

# Scanner configuration
scanners:
  mdns:
    enabled: true
  ssdp:
    enabled: true
  arp:
    enabled: true

# Port scanner configuration
port_scanner:
  timeout: 5s
  # List of TCP ports to scan on discovered devices
  tcp: [21, 22, 23, 25, 80, 110, 135, 139, 143, 389, 443, 445, 993, 995, 1433, 1521, 3306, 3389, 5432, 5900, 8080, 8443, 9000, 9090, 9200, 9300, 10000, 27017]

# Uncomment the next line to configure a specific network interface - uses OS default if not set
# network_interface: eth0
